codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "70...100"

fixes:
  - "bethutil/::"

ignore:
  - "tests/"
  - "build/"
  - "bethutil/" # for some reason, the entire project is being included in the coverage report, duplicating the results
  - "usr/" # for some reason, the entire project is being included in the coverage report, duplicating the results

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false
