#include <btu/common/algorithms.hpp>
#include <btu/common/metaprogramming.hpp>
#include <btu/nif/functions.hpp>
#include <btu/nif/mesh.hpp>
#include <btu/nif/optimize.hpp>

namespace btu::nif {

auto optimize(Mesh file, const OptimizationSteps &sets) -> tl::expected<Mesh, Error>
{
    auto res = tl::expected<Mesh, Error>(std::move(file));
    if (sets.rename_referenced_textures)
        res.map([](auto &m) { rename_referenced_textures(m); });
    if (sets.format)
        res = res.and_then([&](auto &&m) { return convert(BTU_FWD(m), sets.headpart, *sets.format); });
    return res;
}

auto compute_optimization_steps(const Mesh &file, const Settings &sets) -> OptimizationSteps
{
    // We only convert SSE and LE
    std::optional<btu::Game> format{};

    const bool sse_compatible = file.get().IsSSECompatible();
    const bool sse            = sets.game == btu::Game::SSE && !sse_compatible;
    const bool sle            = sets.game == btu::Game::SLE;
    if (sse || sle)
        format = sets.game;

    const auto path        = canonize_path(file.get_load_path());
    const auto is_headpart = btu::common::contains(sets.headpart_meshes, path);

    return OptimizationSteps{
        .rename_referenced_textures = sets.rename_referenced_textures,
        .format                     = format,
        .headpart                   = is_headpart ? HeadpartStatus::Yes : HeadpartStatus::No,
    };
}

auto skyrim_headpart_meshes() noexcept -> const std::vector<std::u8string> &;

auto Settings::get(btu::Game game) noexcept -> const Settings &
{
    switch (game)
    {
        case Game::TES3: static const auto tes3_sets = Settings{.game = game}; return tes3_sets;
        case Game::TES4: static const auto tes4_sets = Settings{.game = game}; return tes4_sets;
        case Game::FNV: static const auto fnv_sets = Settings{.game = game}; return fnv_sets;
        case Game::SLE:
            static const auto sle_sets = Settings{
                .game            = game,
                .headpart_meshes = skyrim_headpart_meshes(),
            };
            return sle_sets;
        case Game::SSE:
            static const auto sse_sets = Settings{
                .game                       = game,
                .rename_referenced_textures = true,
                .headpart_meshes            = skyrim_headpart_meshes(),
            };
            return sse_sets;
        case Game::FO4:
            static const auto fo4_sets = Settings{
                .game                       = game,
                .rename_referenced_textures = true,
            };
            return fo4_sets;
        case Game::Custom: static const auto custom_sets = Settings{.game = game}; return custom_sets;
    }

    static const auto default_sets = Settings{.game = game};
    return default_sets;
}

auto skyrim_headpart_meshes() noexcept -> const std::vector<std::u8string> &
{
    static const auto meshes = [] {
        return std::vector<std::u8string>{
            u8"actors/character/character assets/eyesfemale.nif",
            u8"actors/character/character assets/faceparts/femalebrows.nif",
            u8"actors/character/character assets/femalehead.nif",
            u8"actors/character/character assets/hair/female/hair13.nif",
            u8"actors/character/character assets/eyesfemalevampire.nif",
            u8"actors/character/character assets/eyesmale.nif",
            u8"actors/character/character assets/eyesmalevampire.nif",
            u8"actors/character/character assets/faceparts/malebrows.nif",
            u8"actors/character/character assets/femalehead.nif",
            u8"actors/character/character assets/hair/maledarkelfhair01.nif",
            u8"actors/character/character assets/hair/maledarkelfhair01_hairline.nif",
            u8"actors/character/character assets/hair/maledarkelfhair02.nif",
            u8"actors/character/character assets/hair/maledarkelfhair02_hairline.nif",
            u8"actors/character/character assets/hair/maledarkelfhair03.nif",
            u8"actors/character/character assets/hair/maledarkelfhair03_hairline.nif",
            u8"actors/character/character assets/hair/maledarkelfhair06.nif",
            u8"actors/character/character assets/hair/maledarkelfhair06_hairline.nif",
            u8"actors/character/character assets/malehead.nif",
            u8"actors/dlc01/character/hair/dlc1femaleseranahair.nif",
            u8"actors/dlc01/character/hair/dlc1femaleseranahair_hairline.nif",
            u8"actors/dlc01/character/hair/dlc1femalevalericahair.nif",
            u8"actors/dlc01/character/hair/dlc1femalevalericahair_hairline.nif",
            u8"actors/character/character assets/beards/humanbeardlong01.nif",
            u8"actors/character/character assets/beards/humanbeardlong01_1bit.nif",
            u8"actors/character/character assets/beards/humanbeardlong02.nif",
            u8"actors/character/character assets/beards/humanbeardlong03_1bit.nif",
            u8"actors/character/character assets/beards/humanbeardlong04.nif",
            u8"actors/character/character assets/beards/humanbeardlong04_1bit.nif",
            u8"actors/character/character assets/beards/humanbeardlong05.nif",
            u8"actors/character/character assets/beards/humanbeardlong08_1bit.nif",
            u8"actors/character/character assets/beards/humanbeardlong09_1bit.nif",
            u8"actors/character/character assets/beards/humanbeardlong11.nif",
            u8"actors/character/character assets/beards/humanbeardlong11_1bit.nif",
            u8"actors/character/character assets/beards/humanbeardlong12.nif",
            u8"actors/character/character assets/beards/humanbeardlong12_1bit.nif",
            u8"actors/character/character assets/beards/humanbeardlong13.nif",
            u8"actors/character/character assets/beards/humanbeardlong13_1bit.nif",
            u8"actors/character/character assets/beards/humanbeardlong14.nif",
            u8"actors/character/character assets/beards/humanbeardlong14_1bit.nif",
            u8"actors/character/character assets/beards/humanbeardlong15.nif",
            u8"actors/character/character assets/beards/humanbeardlong15_1bit.nif",
            u8"actors/character/character assets/beards/humanbeardlong16.nif",
            u8"actors/character/character assets/beards/humanbeardlong16_1bit.nif",
            u8"actors/character/character assets/beards/humanbeardlong17.nif",
            u8"actors/character/character assets/beards/humanbeardlong17_1bit.nif",
            u8"actors/character/character assets/beards/humanbeardmedium01.nif",
            u8"actors/character/character assets/beards/humanbeardmedium01_1bit.nif",
            u8"actors/character/character assets/beards/humanbeardmedium03.nif",
            u8"actors/character/character assets/beards/humanbeardmedium03_1bit.nif",
            u8"actors/character/character assets/beards/humanbeardmedium04.nif",
            u8"actors/character/character assets/beards/humanbeardmedium07.nif",
            u8"actors/character/character assets/beards/humanbeardshort01.nif",
            u8"actors/character/character assets/beards/humanbeardshort02.nif",
            u8"actors/character/character assets/beards/humanbeardshort03.nif",
            u8"actors/character/character assets/beards/humanbeardshort04.nif",
            u8"actors/character/character assets/beards/humanbeardshort05.nif",
            u8"actors/character/character assets/beards/humanbeardshort07.nif",
            u8"actors/character/character assets/beards/humanbeardshort08.nif",
            u8"actors/character/character assets/beards/humanbeardshort09.nif",
            u8"actors/character/character assets/beards/humanbeardshort10.nif",
            u8"actors/character/character assets/beards/humanbeardshort11.nif",
            u8"actors/character/character assets/beards/humanbeardshort12.nif",
            u8"actors/character/character assets/beards/humanbeardshort13.nif",
            u8"actors/character/character assets/beards/humanbeardshort14.nif",
            u8"actors/character/character assets/beards/humanbeardshort15.nif",
            u8"actors/character/character assets/beards/humanbeardshort16.nif",
            u8"actors/character/character assets/beards/humanbeardshort17.nif",
            u8"actors/character/character assets/beards/humanbeardshort18.nif",
            u8"actors/character/character assets/beards/humanbeardshort19.nif",
            u8"actors/character/character assets/beards/humanbeardshort20.nif",
            u8"actors/character/character assets/beards/humanbeardshort21.nif",
            u8"actors/character/character assets/beards/humanbeardshort22.nif",
            u8"actors/character/character assets/beards/humanbeardshort23.nif",
            u8"actors/character/character assets/beards/humanbeardshort24.nif",
            u8"actors/character/character assets/beards/humanbeardshort25.nif",
            u8"actors/character/character assets/beards/humanbeardshort26.nif",
            u8"actors/character/character assets/beards/humanbeardshort27.nif",
            u8"actors/character/character assets/beards/humanbeardshort28.nif",
            u8"actors/character/character assets/beards/humanbeardshort29.nif",
            u8"actors/character/character assets/beards/humanbeardshort30.nif",
            u8"actors/character/character assets/beards/humanbeardshort31.nif",
            u8"actors/character/character assets/beards/humanbeardshort32.nif",
            u8"actors/character/character assets/beards/khajiitbeard.nif",
            u8"actors/character/character assets/beards/khajiitbeard01.nif",
            u8"actors/character/character assets/beards/khajiitbeard02.nif",
            u8"actors/character/character assets/beards/khajiitbeardalpha.nif",
            u8"actors/character/character assets/beards/khajiitmustache01.nif",
            u8"actors/character/character assets/beards/khajiitmustache01alpha.nif",
            u8"actors/character/character assets/beards/khajiitmustache02.nif",
            u8"actors/character/character assets/beards/khajiitmustache02alpha.nif",
            u8"actors/character/character assets/childhead.nif",
            u8"actors/character/character assets/eyesargonian.nif",
            u8"actors/character/character assets/eyeschild.nif",
            u8"actors/character/character assets/eyesfemale.nif",
            u8"actors/character/character assets/eyeskhajiit.nif",
            u8"actors/character/character assets/eyeskhajiitfemale.nif",
            u8"actors/character/character assets/eyesmale.nif",
            u8"actors/character/character assets/faceparts/argonianbrow01.nif",
            u8"actors/character/character assets/faceparts/argonianbrow02.nif",
            u8"actors/character/character assets/faceparts/eyefemaleleft.nif",
            u8"actors/character/character assets/faceparts/eyefemaleright.nif",
            u8"actors/character/character assets/faceparts/eyesmaleleft.nif",
            u8"actors/character/character assets/faceparts/eyesmaleright.nif",
            u8"actors/character/character assets/faceparts/femaleargonianscar.nif",
            u8"actors/character/character assets/faceparts/femaleargonianscar01.nif",
            u8"actors/character/character assets/faceparts/femaleargonianscar02.nif",
            u8"actors/character/character assets/faceparts/femaleargonianscar03.nif",
            u8"actors/character/character assets/faceparts/femaleargonianscar04.nif",
            u8"actors/character/character assets/faceparts/femaleargonianscar05.nif",
            u8"actors/character/character assets/faceparts/femalebrows.nif",
            u8"actors/character/character assets/faceparts/femalemaskleftside.nif",
            u8"actors/character/character assets/faceparts/femalemaskrightside.nif",
            u8"actors/character/character assets/faceparts/khajiitearrings.nif",
            u8"actors/character/character assets/faceparts/khajiitearrings01.nif",
            u8"actors/character/character assets/faceparts/khajiitearrings02.nif",
            u8"actors/character/character assets/faceparts/khajiitearrings03.nif",
            u8"actors/character/character assets/faceparts/khajiitearrings04.nif",
            u8"actors/character/character assets/faceparts/khajiitearrings05.nif",
            u8"actors/character/character assets/faceparts/khajiitearrings06.nif",
            u8"actors/character/character assets/faceparts/khajiitfemalescar01.nif",
            u8"actors/character/character assets/faceparts/khajiitfemalescar02.nif",
            u8"actors/character/character assets/faceparts/khajiitfemalescar03.nif",
            u8"actors/character/character assets/faceparts/maleargonianscar.nif",
            u8"actors/character/character assets/faceparts/maleargonianscar01.nif",
            u8"actors/character/character assets/faceparts/maleargonianscar02.nif",
            u8"actors/character/character assets/faceparts/maleargonianscar03.nif",
            u8"actors/character/character assets/faceparts/maleargonianscar04.nif",
            u8"actors/character/character assets/faceparts/malebrows.nif",
            u8"actors/character/character assets/faceparts/malekhajiitscar01.nif",
            u8"actors/character/character assets/faceparts/malekhajiitscar02.nif",
            u8"actors/character/character assets/faceparts/malekhajiitscar03.nif",
            u8"actors/character/character assets/faceparts/maskleftside.nif",
            u8"actors/character/character assets/faceparts/maskrightside.nif",
            u8"actors/character/character assets/faceparts/orcbrows_01.nif",
            u8"actors/character/character assets/faceparts/orcbrows_02.nif",
            u8"actors/character/character assets/faceparts/orcbrows_03.nif",
            u8"actors/character/character assets/faceparts/orcbrows_04.nif",
            u8"actors/character/character assets/faceparts/orcbrows_05.nif",
            u8"actors/character/character assets/femalehead.nif",
            u8"actors/character/character assets/femaleheadargonian.nif",
            u8"actors/character/character assets/femaleheadkhajiit.nif",
            u8"actors/character/character assets/hair/argonianfemalehorns01.nif",
            u8"actors/character/character assets/hair/argonianfemalehorns01hairline.nif",
            u8"actors/character/character assets/hair/argonianfemalehorns02.nif",
            u8"actors/character/character assets/hair/argonianfemalehorns03.nif",
            u8"actors/character/character assets/hair/argonianfemalehorns03hairline.nif",
            u8"actors/character/character assets/hair/argonianfemalehorns04.nif",
            u8"actors/character/character assets/hair/argonianfemalehorns04hairline.nif",
            u8"actors/character/character assets/hair/argonianfemalehorns05.nif",
            u8"actors/character/character assets/hair/argonianfemalehorns05hairline.nif",
            u8"actors/character/character assets/hair/argonianfemalehorns06.nif",
            u8"actors/character/character assets/hair/argonianfemalehorns06hairline.nif",
            u8"actors/character/character assets/hair/argonianfemalehorns07.nif",
            u8"actors/character/character assets/hair/argonianfemalehorns08.nif",
            u8"actors/character/character assets/hair/argonianfemalehorns09.nif",
            u8"actors/character/character assets/hair/argonianfemalehorns09ahairline.nif",
            u8"actors/character/character assets/hair/argonianfemalehorns09bhairline.nif",
            u8"actors/character/character assets/hair/argonianmalehorns01.nif",
            u8"actors/character/character assets/hair/argonianmalehorns02.nif",
            u8"actors/character/character assets/hair/argonianmalehorns03.nif",
            u8"actors/character/character assets/hair/argonianmalehorns04.nif",
            u8"actors/character/character assets/hair/argonianmalehorns04hairline.nif",
            u8"actors/character/character assets/hair/argonianmalehorns05.nif",
            u8"actors/character/character assets/hair/argonianmalehorns06.nif",
            u8"actors/character/character assets/hair/argonianmalehorns07.nif",
            u8"actors/character/character assets/hair/argonianmalehorns07hairline.nif",
            u8"actors/character/character assets/hair/argonianmalehorns08.nif",
            u8"actors/character/character assets/hair/argonianmalehorns09.nif",
            u8"actors/character/character assets/hair/argonianmalehorns10.nif",
            u8"actors/character/character assets/hair/argonianmalehorns10hairline.nif",
            u8"actors/character/character assets/hair/elf/female/hair01.nif",
            u8"actors/character/character assets/hair/elf/female/hair02.nif",
            u8"actors/character/character assets/hair/elf/female/hair03.nif",
            u8"actors/character/character assets/hair/elf/female/hair04.nif",
            u8"actors/character/character assets/hair/elf/female/hair05.nif",
            u8"actors/character/character assets/hair/elf/female/hair06.nif",
            u8"actors/character/character assets/hair/elf/female/hair07.nif",
            u8"actors/character/character assets/hair/elf/female/hair08.nif",
            u8"actors/character/character assets/hair/elf/female/hair09.nif",
            u8"actors/character/character assets/hair/elf/female/hair10.nif",
            u8"actors/character/character assets/hair/elf/female/hairline01.nif",
            u8"actors/character/character assets/hair/elf/female/hairline02.nif",
            u8"actors/character/character assets/hair/elf/female/hairline03.nif",
            u8"actors/character/character assets/hair/elf/female/hairline04.nif",
            u8"actors/character/character assets/hair/elf/female/hairline05.nif",
            u8"actors/character/character assets/hair/elf/female/hairline06.nif",
            u8"actors/character/character assets/hair/elf/female/hairline07.nif",
            u8"actors/character/character assets/hair/elf/female/hairline08.nif",
            u8"actors/character/character assets/hair/elf/female/hairline09.nif",
            u8"actors/character/character assets/hair/elf/female/hairline10.nif",
            u8"actors/character/character assets/hair/elf/male/hair01.nif",
            u8"actors/character/character assets/hair/elf/male/hair02.nif",
            u8"actors/character/character assets/hair/elf/male/hair03.nif",
            u8"actors/character/character assets/hair/elf/male/hair04.nif",
            u8"actors/character/character assets/hair/elf/male/hair05.nif",
            u8"actors/character/character assets/hair/elf/male/hair06.nif",
            u8"actors/character/character assets/hair/elf/male/hair07.nif",
            u8"actors/character/character assets/hair/elf/male/hair08.nif",
            u8"actors/character/character assets/hair/elf/male/hair09.nif",
            u8"actors/character/character assets/hair/elf/male/hairline01.nif",
            u8"actors/character/character assets/hair/elf/male/hairline02.nif",
            u8"actors/character/character assets/hair/elf/male/hairline03.nif",
            u8"actors/character/character assets/hair/elf/male/hairline04.nif",
            u8"actors/character/character assets/hair/elf/male/hairline05.nif",
            u8"actors/character/character assets/hair/elf/male/hairline06.nif",
            u8"actors/character/character assets/hair/elf/male/hairline07.nif",
            u8"actors/character/character assets/hair/elf/male/hairline08.nif",
            u8"actors/character/character assets/hair/elf/male/hairline09.nif",
            u8"actors/character/character assets/hair/female/hair01.nif",
            u8"actors/character/character assets/hair/female/hair02.nif",
            u8"actors/character/character assets/hair/female/hair03.nif",
            u8"actors/character/character assets/hair/female/hair04.nif",
            u8"actors/character/character assets/hair/female/hair05.nif",
            u8"actors/character/character assets/hair/female/hair06.nif",
            u8"actors/character/character assets/hair/female/hair07.nif",
            u8"actors/character/character assets/hair/female/hair08.nif",
            u8"actors/character/character assets/hair/female/hair09.nif",
            u8"actors/character/character assets/hair/female/hair10.nif",
            u8"actors/character/character assets/hair/female/hair11.nif",
            u8"actors/character/character assets/hair/female/hair12.nif",
            u8"actors/character/character assets/hair/female/hair13.nif",
            u8"actors/character/character assets/hair/female/hair14.nif",
            u8"actors/character/character assets/hair/female/hair15.nif",
            u8"actors/character/character assets/hair/female/hair16.nif",
            u8"actors/character/character assets/hair/female/hair17.nif",
            u8"actors/character/character assets/hair/female/hair18.nif",
            u8"actors/character/character assets/hair/female/hair19.nif",
            u8"actors/character/character assets/hair/female/hair20.nif",
            u8"actors/character/character assets/hair/female/hair21.nif",
            u8"actors/character/character assets/hair/female/hairline01.nif",
            u8"actors/character/character assets/hair/female/hairline02.nif",
            u8"actors/character/character assets/hair/female/hairline03.nif",
            u8"actors/character/character assets/hair/female/hairline04.nif",
            u8"actors/character/character assets/hair/female/hairline05.nif",
            u8"actors/character/character assets/hair/female/hairline06.nif",
            u8"actors/character/character assets/hair/female/hairline07.nif",
            u8"actors/character/character assets/hair/female/hairline08.nif",
            u8"actors/character/character assets/hair/female/hairline09.nif",
            u8"actors/character/character assets/hair/female/hairline10.nif",
            u8"actors/character/character assets/hair/female/hairline11.nif",
            u8"actors/character/character assets/hair/female/hairline12.nif",
            u8"actors/character/character assets/hair/female/hairline13.nif",
            u8"actors/character/character assets/hair/female/hairline14.nif",
            u8"actors/character/character assets/hair/female/hairline15.nif",
            u8"actors/character/character assets/hair/female/hairline16.nif",
            u8"actors/character/character assets/hair/female/hairline17.nif",
            u8"actors/character/character assets/hair/female/hairline18.nif",
            u8"actors/character/character assets/hair/female/hairline19.nif",
            u8"actors/character/character assets/hair/female/hairline20.nif",
            u8"actors/character/character assets/hair/female/hairline21.nif",
            u8"actors/character/character assets/hair/femalechildnordhair01.nif",
            u8"actors/character/character assets/hair/femalechildnordhair01_hairline.nif",
            u8"actors/character/character assets/hair/femalechildnordhair02.nif",
            u8"actors/character/character assets/hair/femalechildnordhair02_hairline.nif",
            u8"actors/character/character assets/hair/femalechildredguardhair01.nif",
            u8"actors/character/character assets/hair/femaledarkelfhair01.nif",
            u8"actors/character/character assets/hair/femaledarkelfhair01_hairline.nif",
            u8"actors/character/character assets/hair/femaledarkelfhair02.nif",
            u8"actors/character/character assets/hair/femaledarkelfhair02_hairline.nif",
            u8"actors/character/character assets/hair/femaledarkelfhair03.nif",
            u8"actors/character/character assets/hair/femaledarkelfhair03_hairline.nif",
            u8"actors/character/character assets/hair/femaledarkelfhair04.nif",
            u8"actors/character/character assets/hair/femaledarkelfhair05.nif",
            u8"actors/character/character assets/hair/femaledarkelfhair05_hairline.nif",
            u8"actors/character/character assets/hair/femaledarkelfhair06.nif",
            u8"actors/character/character assets/hair/femaledarkelfhair06_hairline.nif",
            u8"actors/character/character assets/hair/femaledarkelfhair06_shaved.nif",
            u8"actors/character/character assets/hair/femaledarkelfhair07.nif",
            u8"actors/character/character assets/hair/femaledarkelfhair08.nif",
            u8"actors/character/character assets/hair/femaledarkelfhair08_hairline.nif",
            u8"actors/character/character assets/hair/femaledarkelfhair08_shaved.nif",
            u8"actors/character/character assets/hair/femaledremora01_hairline.nif",
            u8"actors/character/character assets/hair/femaledremora02_hairline.nif",
            u8"actors/character/character assets/hair/femaledremorahair01.nif",
            u8"actors/character/character assets/hair/femaledremorahair02.nif",
            u8"actors/character/character assets/hair/femalehumanoldhair01_hairline.nif",
            u8"actors/character/character assets/hair/femaleorchair01.nif",
            u8"actors/character/character assets/hair/femaleorchair01_hairline.nif",
            u8"actors/character/character assets/hair/femaleorchair02.nif",
            u8"actors/character/character assets/hair/femaleorchair03.nif",
            u8"actors/character/character assets/hair/femaleorchair03_hairline.nif",
            u8"actors/character/character assets/hair/femaleorchair04.nif",
            u8"actors/character/character assets/hair/femaleorchair05.nif",
            u8"actors/character/character assets/hair/femaleorchair05_hairline.nif",
            u8"actors/character/character assets/hair/femaleorchair06.nif",
            u8"actors/character/character assets/hair/femaleorchair06_hairline.nif",
            u8"actors/character/character assets/hair/femaleorchair07.nif",
            u8"actors/character/character assets/hair/femaleorchair07_hairline.nif",
            u8"actors/character/character assets/hair/femaleorchair08.nif",
            u8"actors/character/character assets/hair/femaleorchair08_hairline.nif",
            u8"actors/character/character assets/hair/femaleorchair09.nif",
            u8"actors/character/character assets/hair/femaleorchair09_hairline.nif",
            u8"actors/character/character assets/hair/femaleorchair10.nif",
            u8"actors/character/character assets/hair/femaleorchair11.nif",
            u8"actors/character/character assets/hair/femaleorchair11_hairline.nif",
            u8"actors/character/character assets/hair/femaleorchair12.nif",
            u8"actors/character/character assets/hair/femaleorchair13.nif",
            u8"actors/character/character assets/hair/femaleorchair14.nif",
            u8"actors/character/character assets/hair/femaleorchair14_hairline.nif",
            u8"actors/character/character assets/hair/femaleorchair14_shaved.nif",
            u8"actors/character/character assets/hair/femaleorchair15.nif",
            u8"actors/character/character assets/hair/femaleorchair17.nif",
            u8"actors/character/character assets/hair/femaleorchair17_hairline.nif",
            u8"actors/character/character assets/hair/femaleredguardhair01.nif",
            u8"actors/character/character assets/hair/femaleredguardhair02.nif",
            u8"actors/character/character assets/hair/femaleredguardhair03.nif",
            u8"actors/character/character assets/hair/femaleredguardhair04.nif",
            u8"actors/character/character assets/hair/hairshorthumanf.nif",
            u8"actors/character/character assets/hair/hairshorthumanm.nif",
            u8"actors/character/character assets/hair/khajiit/female/hair01.nif",
            u8"actors/character/character assets/hair/khajiit/female/hair02.nif",
            u8"actors/character/character assets/hair/khajiit/female/hair03.nif",
            u8"actors/character/character assets/hair/khajiit/female/hair04.nif",
            u8"actors/character/character assets/hair/khajiit/female/hair05.nif",
            u8"actors/character/character assets/hair/khajiit/female/hair06.nif",
            u8"actors/character/character assets/hair/khajiit/female/hairline01.nif",
            u8"actors/character/character assets/hair/khajiit/female/hairline02.nif",
            u8"actors/character/character assets/hair/khajiit/female/hairline03.nif",
            u8"actors/character/character assets/hair/khajiit/female/hairline04.nif",
            u8"actors/character/character assets/hair/khajiit/female/hairline05.nif",
            u8"actors/character/character assets/hair/khajiit/female/hairline06.nif",
            u8"actors/character/character assets/hair/khajiit/male/eartufts.nif",
            u8"actors/character/character assets/hair/khajiit/male/eartuftsbase.nif",
            u8"actors/character/character assets/hair/khajiit/male/khajiithair01.nif",
            u8"actors/character/character assets/hair/khajiit/male/khajiithair02.nif",
            u8"actors/character/character assets/hair/khajiit/male/khajiithair03.nif",
            u8"actors/character/character assets/hair/khajiit/male/khajiithair04.nif",
            u8"actors/character/character assets/hair/khajiit/male/khajiithair05.nif",
            u8"actors/character/character assets/hair/khajiit/male/khajiithair06.nif",
            u8"actors/character/character assets/hair/khajiit/male/khajiithair07.nif",
            u8"actors/character/character assets/hair/khajiit/male/khajiithair08.nif",
            u8"actors/character/character assets/hair/khajiit/male/khajiithair09.nif",
            u8"actors/character/character assets/hair/khajiit/male/khajiithairline01.nif",
            u8"actors/character/character assets/hair/khajiit/male/khajiithairline02.nif",
            u8"actors/character/character assets/hair/khajiit/male/khajiithairline03.nif",
            u8"actors/character/character assets/hair/khajiit/male/khajiithairline04.nif",
            u8"actors/character/character assets/hair/khajiit/male/khajiithairline05.nif",
            u8"actors/character/character assets/hair/khajiit/male/khajiithairline06.nif",
            u8"actors/character/character assets/hair/khajiit/male/khajiithairline07.nif",
            u8"actors/character/character assets/hair/khajiit/male/khajiithairline08.nif",
            u8"actors/character/character assets/hair/khajiit/male/khajiithairline09.nif",
            u8"actors/character/character assets/hair/khajiiteartuftsbasefemale.nif",
            u8"actors/character/character assets/hair/male/hair01.nif",
            u8"actors/character/character assets/hair/male/hair02.nif",
            u8"actors/character/character assets/hair/male/hair03.nif",
            u8"actors/character/character assets/hair/male/hair04.nif",
            u8"actors/character/character assets/hair/male/hair05.nif",
            u8"actors/character/character assets/hair/male/hair06.nif",
            u8"actors/character/character assets/hair/male/hair07.nif",
            u8"actors/character/character assets/hair/male/hair08.nif",
            u8"actors/character/character assets/hair/male/hair09.nif",
            u8"actors/character/character assets/hair/male/hair10.nif",
            u8"actors/character/character assets/hair/male/hair11.nif",
            u8"actors/character/character assets/hair/male/hair12.nif",
            u8"actors/character/character assets/hair/male/hair13.nif",
            u8"actors/character/character assets/hair/male/hair14.nif",
            u8"actors/character/character assets/hair/male/hair15.nif",
            u8"actors/character/character assets/hair/male/hair16.nif",
            u8"actors/character/character assets/hair/male/hair17.nif",
            u8"actors/character/character assets/hair/male/hair18.nif",
            u8"actors/character/character assets/hair/male/hair19.nif",
            u8"actors/character/character assets/hair/male/hair20.nif",
            u8"actors/character/character assets/hair/male/hairline01.nif",
            u8"actors/character/character assets/hair/male/hairline02.nif",
            u8"actors/character/character assets/hair/male/hairline03.nif",
            u8"actors/character/character assets/hair/male/hairline04.nif",
            u8"actors/character/character assets/hair/male/hairline05.nif",
            u8"actors/character/character assets/hair/male/hairline06.nif",
            u8"actors/character/character assets/hair/male/hairline07.nif",
            u8"actors/character/character assets/hair/male/hairline08.nif",
            u8"actors/character/character assets/hair/male/hairline09.nif",
            u8"actors/character/character assets/hair/male/hairline10.nif",
            u8"actors/character/character assets/hair/male/hairline11.nif",
            u8"actors/character/character assets/hair/male/hairline12.nif",
            u8"actors/character/character assets/hair/male/hairline13.nif",
            u8"actors/character/character assets/hair/male/hairline14.nif",
            u8"actors/character/character assets/hair/male/hairline15.nif",
            u8"actors/character/character assets/hair/male/hairline16.nif",
            u8"actors/character/character assets/hair/male/hairline17.nif",
            u8"actors/character/character assets/hair/male/hairline18.nif",
            u8"actors/character/character assets/hair/male/hairline19.nif",
            u8"actors/character/character assets/hair/male/hairline20.nif",
            u8"actors/character/character assets/hair/malechildimperialhair01.nif",
            u8"actors/character/character assets/hair/malechildimperialhair01_hairline.nif",
            u8"actors/character/character assets/hair/malechildnordhair01.nif",
            u8"actors/character/character assets/hair/malechildnordhair01_hairline.nif",
            u8"actors/character/character assets/hair/malechildredguardhair01.nif",
            u8"actors/character/character assets/hair/malechildredguardhair01_hairline.nif",
            u8"actors/character/character assets/hair/maledarkelfhair01.nif",
            u8"actors/character/character assets/hair/maledarkelfhair01_hairline.nif",
            u8"actors/character/character assets/hair/maledarkelfhair02.nif",
            u8"actors/character/character assets/hair/maledarkelfhair02_hairline.nif",
            u8"actors/character/character assets/hair/maledarkelfhair03.nif",
            u8"actors/character/character assets/hair/maledarkelfhair03_hairline.nif",
            u8"actors/character/character assets/hair/maledarkelfhair04.nif",
            u8"actors/character/character assets/hair/maledarkelfhair04_hairline.nif",
            u8"actors/character/character assets/hair/maledarkelfhair04_shaved.nif",
            u8"actors/character/character assets/hair/maledarkelfhair05.nif",
            u8"actors/character/character assets/hair/maledarkelfhair05_hairline.nif",
            u8"actors/character/character assets/hair/maledarkelfhair05_shaved.nif",
            u8"actors/character/character assets/hair/maledarkelfhair06.nif",
            u8"actors/character/character assets/hair/maledarkelfhair06_hairline.nif",
            u8"actors/character/character assets/hair/maledarkelfhair07.nif",
            u8"actors/character/character assets/hair/maledarkelfhair08.nif",
            u8"actors/character/character assets/hair/maledarkelfhair08_hairline.nif",
            u8"actors/character/character assets/hair/maledarkelfhair09.nif",
            u8"actors/character/character assets/hair/maledarkelfhair09_hairline.nif",
            u8"actors/character/character assets/hair/maledarkelfhair09_shaved.nif",
            u8"actors/character/character assets/hair/maledremorahair01.nif",
            u8"actors/character/character assets/hair/maledremorahair01_hairline.nif",
            u8"actors/character/character assets/hair/maledremorahair01_horns.nif",
            u8"actors/character/character assets/hair/maledremorahair02.nif",
            u8"actors/character/character assets/hair/maledremorahair02_hairline.nif",
            u8"actors/character/character assets/hair/maledremorahair02_horns.nif",
            u8"actors/character/character assets/hair/malehumanoldhair01.nif",
            u8"actors/character/character assets/hair/malehumanoldhair02.nif",
            u8"actors/character/character assets/hair/malehumanoldhair03.nif",
            u8"actors/character/character assets/hair/malehumanoldhair04.nif",
            u8"actors/character/character assets/hair/malehumanoldhair04_hairline.nif",
            u8"actors/character/character assets/hair/malehumanoldhair05.nif",
            u8"actors/character/character assets/hair/malehumanoldhair05_hairline.nif",
            u8"actors/character/character assets/hair/malehumanoldhair06.nif",
            u8"actors/character/character assets/hair/malehumanoldhair06_hairline.nif",
            u8"actors/character/character assets/hair/maleorchair01.nif",
            u8"actors/character/character assets/hair/maleorchair01_hairline.nif",
            u8"actors/character/character assets/hair/maleorchair02.nif",
            u8"actors/character/character assets/hair/maleorchair02_hairline.nif",
            u8"actors/character/character assets/hair/maleorchair03.nif",
            u8"actors/character/character assets/hair/maleorchair04.nif",
            u8"actors/character/character assets/hair/maleorchair05.nif",
            u8"actors/character/character assets/hair/maleorchair06.nif",
            u8"actors/character/character assets/hair/maleorchair07.nif",
            u8"actors/character/character assets/hair/maleorchair08.nif",
            u8"actors/character/character assets/hair/maleorchair08_hairline.nif",
            u8"actors/character/character assets/hair/maleorchair08_shaved.nif",
            u8"actors/character/character assets/hair/maleorchair09.nif",
            u8"actors/character/character assets/hair/maleorchair10.nif",
            u8"actors/character/character assets/hair/maleorchair11.nif",
            u8"actors/character/character assets/hair/maleorchair12.nif",
            u8"actors/character/character assets/hair/maleorchair12_hairline.nif",
            u8"actors/character/character assets/hair/maleorchair12_shaved.nif",
            u8"actors/character/character assets/hair/maleorchair13.nif",
            u8"actors/character/character assets/hair/maleorchair14.nif",
            u8"actors/character/character assets/hair/maleorchair15.nif",
            u8"actors/character/character assets/hair/maleorchair15_hairline.nif",
            u8"actors/character/character assets/hair/maleorchair15_shaved.nif",
            u8"actors/character/character assets/hair/maleorchair16.nif",
            u8"actors/character/character assets/hair/maleorchair17.nif",
            u8"actors/character/character assets/hair/maleorchair18.nif",
            u8"actors/character/character assets/hair/maleorchair18_hairline.nif",
            u8"actors/character/character assets/hair/maleorchair19.nif",
            u8"actors/character/character assets/hair/maleorchair20.nif",
            u8"actors/character/character assets/hair/maleorchair21.nif",
            u8"actors/character/character assets/hair/maleorchair21_hairline.nif",
            u8"actors/character/character assets/hair/maleorchair22.nif",
            u8"actors/character/character assets/hair/maleorchair23.nif",
            u8"actors/character/character assets/hair/maleorchair24.nif",
            u8"actors/character/character assets/hair/maleorchair24_hairline.nif",
            u8"actors/character/character assets/hair/maleorchair25.nif",
            u8"actors/character/character assets/hair/maleorchair26.nif",
            u8"actors/character/character assets/hair/maleorchair26_hairline.nif",
            u8"actors/character/character assets/hair/maleorchair27.nif",
            u8"actors/character/character assets/hair/maleorchair27_hairline.nif",
            u8"actors/character/character assets/hair/maleredguardhair01.nif",
            u8"actors/character/character assets/hair/maleredguardhair02.nif",
            u8"actors/character/character assets/hair/maleredguardhair03.nif",
            u8"actors/character/character assets/hair/maleredguardhair03_hairline.nif",
            u8"actors/character/character assets/hair/maleredguardhair04.nif",
            u8"actors/character/character assets/hair/maleredguardhair04_hairline.nif",
            u8"actors/character/character assets/hair/maleredguardhair05.nif",
            u8"actors/character/character assets/hair/maleredguardhair05_hairline.nif",
            u8"actors/character/character assets/hair/maleredguardhair06.nif",
            u8"actors/character/character assets/hair/maleredguardhair06b.nif",
            u8"actors/character/character assets/hair/maleredguardhair07a.nif",
            u8"actors/character/character assets/hair/maleredguardhair07b.nif",
            u8"actors/character/character assets/hair/maleredguardhair07c.nif",
            u8"actors/character/character assets/hair/maleredguardhair08.nif",
            u8"actors/character/character assets/hair/maleredguardhair08_hairline.nif",
            u8"actors/character/character assets/malehead.nif",
            u8"actors/character/character assets/maleheadargonian.nif",
            u8"actors/character/character assets/maleheadkhajiit.nif",
            u8"actors/character/character assets/mouth/malemouthkhajiit.nif",
            u8"actors/character/character assets/mouth/mouthargonian.nif",
            u8"actors/character/character assets/mouth/mouthchild.nif",
            u8"actors/character/character assets/mouth/mouthhuman.nif",
            u8"actors/character/character assets/mouth/mouthhumanf.nif",
            u8"actors/character/character assets/mouth/mouthkhajiitfemale.nif",
            u8"actors/character/character assets/mouth/mouthorc.nif",
            u8"actors/character/character assets/mouth/mouthorcfemale.nif",
            u8"actors/manekin/manekinhead.nif",
        };
    }();
    return meshes;
}
} // namespace btu::nif
