name: Apply Formatting

on:
  push:
    branches-ignore:
      - main

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run clang-format
      run: find -type f \( -name *.hpp -o -name *.cpp \) | xargs clang-format-14 -style=file -i

    - name: Format CMake files
      id: cmake-format
      uses: PuneetMatharu/cmake-format-lint-action@v1.0.0
      with:
        args: --in-place
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "style: apply formatting"
