name: Apply Formatting

on: [ push, pull_request, pull_request_target ]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run clang-format
      run: find -type f \( -name *.hpp -o -name *.cpp \) | xargs clang-format-12 -style=file -i

    - name: Format CMake files
      id: cmake-format
      uses: PuneetMatharu/cmake-format-lint-action@v1.0.0
      with:
        args: --in-place
        
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: apply formatting
